version: '3.8'

services:
  app:
    image: maven:3.8.4-openjdk-17
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password
    volumes:
      - ./:/app
    command: ["sh", "-c", "cd app && mvn spring-boot:run"]
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb_db
    environment:
      - MARIADB_ROOT_PASSWORD=your_password
      - MARIADB_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
